package Sedna;

use 5.010000;
use strict;
use warnings;
use Carp;

require Exporter;
use AutoLoader;

our @ISA = qw(Exporter);

# Items to export into callers namespace by default. Note: do not export
# names by default without a very good reason. Use EXPORT_OK instead.
# Do not simply export all your public functions/methods/constants.

# This allows declaration	use Sedna ':all';
# If you do not need this, moving things directly into @EXPORT or @EXPORT_OK
# will save memory.
our %EXPORT_TAGS = ( 'all' => [ qw(
	BULK_LOAD_PORTION
	QUERY_EXECUTION_TIME
	SEDNA_AUTHENTICATION_FAILED
	SEDNA_AUTOCOMMIT_OFF
	SEDNA_AUTOCOMMIT_ON
	SEDNA_BEGIN_TRANSACTION_FAILED
	SEDNA_BEGIN_TRANSACTION_SUCCEEDED
	SEDNA_BOUNDARY_SPACE_PRESERVE_OFF
	SEDNA_BOUNDARY_SPACE_PRESERVE_ON
	SEDNA_BULK_LOAD_FAILED
	SEDNA_BULK_LOAD_SUCCEEDED
	SEDNA_CLOSE_SESSION_FAILED
	SEDNA_COMMIT_TRANSACTION_FAILED
	SEDNA_COMMIT_TRANSACTION_SUCCEEDED
	SEDNA_CONNECTION_CLOSED
	SEDNA_CONNECTION_FAILED
	SEDNA_CONNECTION_OK
	SEDNA_DATA_CHUNK_LOADED
	SEDNA_ERROR
	SEDNA_GET_ATTRIBUTE_SUCCEEDED
	SEDNA_NEXT_ITEM_FAILED
	SEDNA_NEXT_ITEM_SUCCEEDED
	SEDNA_NO_ITEM
	SEDNA_NO_TRANSACTION
	SEDNA_OPEN_SESSION_FAILED
	SEDNA_OPERATION_SUCCEEDED
	SEDNA_QUERY_FAILED
	SEDNA_QUERY_SUCCEEDED
	SEDNA_RESET_ATTRIBUTES_SUCCEEDED
	SEDNA_RESULT_END
	SEDNA_ROLLBACK_TRANSACTION_FAILED
	SEDNA_ROLLBACK_TRANSACTION_SUCCEEDED
	SEDNA_SESSION_CLOSED
	SEDNA_SESSION_OPEN
	SEDNA_SET_ATTRIBUTE_SUCCEEDED
	SEDNA_TRANSACTION_ACTIVE
	SEDNA_UPDATE_FAILED
	SEDNA_UPDATE_SUCCEEDED
) ] );

our @EXPORT_OK = ( @{ $EXPORT_TAGS{'all'} } );

our @EXPORT = qw(
	BULK_LOAD_PORTION
	QUERY_EXECUTION_TIME
	SEDNA_AUTHENTICATION_FAILED
	SEDNA_AUTOCOMMIT_OFF
	SEDNA_AUTOCOMMIT_ON
	SEDNA_BEGIN_TRANSACTION_FAILED
	SEDNA_BEGIN_TRANSACTION_SUCCEEDED
	SEDNA_BOUNDARY_SPACE_PRESERVE_OFF
	SEDNA_BOUNDARY_SPACE_PRESERVE_ON
	SEDNA_BULK_LOAD_FAILED
	SEDNA_BULK_LOAD_SUCCEEDED
	SEDNA_CLOSE_SESSION_FAILED
	SEDNA_COMMIT_TRANSACTION_FAILED
	SEDNA_COMMIT_TRANSACTION_SUCCEEDED
	SEDNA_CONNECTION_CLOSED
	SEDNA_CONNECTION_FAILED
	SEDNA_CONNECTION_OK
	SEDNA_DATA_CHUNK_LOADED
	SEDNA_ERROR
	SEDNA_GET_ATTRIBUTE_SUCCEEDED
	SEDNA_NEXT_ITEM_FAILED
	SEDNA_NEXT_ITEM_SUCCEEDED
	SEDNA_NO_ITEM
	SEDNA_NO_TRANSACTION
	SEDNA_OPEN_SESSION_FAILED
	SEDNA_OPERATION_SUCCEEDED
	SEDNA_QUERY_FAILED
	SEDNA_QUERY_SUCCEEDED
	SEDNA_RESET_ATTRIBUTES_SUCCEEDED
	SEDNA_RESULT_END
	SEDNA_ROLLBACK_TRANSACTION_FAILED
	SEDNA_ROLLBACK_TRANSACTION_SUCCEEDED
	SEDNA_SESSION_CLOSED
	SEDNA_SESSION_OPEN
	SEDNA_SET_ATTRIBUTE_SUCCEEDED
	SEDNA_TRANSACTION_ACTIVE
	SEDNA_UPDATE_FAILED
	SEDNA_UPDATE_SUCCEEDED
);

our $VERSION = '0.01';

sub AUTOLOAD {
    # This AUTOLOAD is used to 'autoload' constants from the constant()
    # XS function.

    my $constname;
    our $AUTOLOAD;
    ($constname = $AUTOLOAD) =~ s/.*:://;
    croak "&Sedna::constant not defined" if $constname eq 'constant';
    my ($error, $val) = constant($constname);
    if ($error) { croak $error; }
    {
	no strict 'refs';
	# Fixed between 5.005_53 and 5.005_61
#XXX	if ($] >= 5.00561) {
#XXX	    *$AUTOLOAD = sub () { $val };
#XXX	}
#XXX	else {
	    *$AUTOLOAD = sub { $val };
#XXX	}
    }
    goto &$AUTOLOAD;
}

require XSLoader;
XSLoader::load('Sedna', $VERSION);

# Preloaded methods go here.

# Autoload methods go after =cut, and are processed by the autosplit program.

1;
__END__
# Below is stub documentation for your module. You'd better edit it!

=head1 NAME

Sedna - Perl extension for blah blah blah

=head1 SYNOPSIS

  use Sedna;
  blah blah blah

=head1 DESCRIPTION

Stub documentation for Sedna, created by h2xs. It looks like the
author of the extension was negligent enough to leave the stub
unedited.

Blah blah blah.

=head2 EXPORT

None by default.

=head2 Exportable constants

  BULK_LOAD_PORTION
  QUERY_EXECUTION_TIME
  SEDNA_AUTHENTICATION_FAILED
  SEDNA_AUTOCOMMIT_OFF
  SEDNA_AUTOCOMMIT_ON
  SEDNA_BEGIN_TRANSACTION_FAILED
  SEDNA_BEGIN_TRANSACTION_SUCCEEDED
  SEDNA_BOUNDARY_SPACE_PRESERVE_OFF
  SEDNA_BOUNDARY_SPACE_PRESERVE_ON
  SEDNA_BULK_LOAD_FAILED
  SEDNA_BULK_LOAD_SUCCEEDED
  SEDNA_CLOSE_SESSION_FAILED
  SEDNA_COMMIT_TRANSACTION_FAILED
  SEDNA_COMMIT_TRANSACTION_SUCCEEDED
  SEDNA_CONNECTION_CLOSED
  SEDNA_CONNECTION_FAILED
  SEDNA_CONNECTION_OK
  SEDNA_DATA_CHUNK_LOADED
  SEDNA_ERROR
  SEDNA_GET_ATTRIBUTE_SUCCEEDED
  SEDNA_NEXT_ITEM_FAILED
  SEDNA_NEXT_ITEM_SUCCEEDED
  SEDNA_NO_ITEM
  SEDNA_NO_TRANSACTION
  SEDNA_OPEN_SESSION_FAILED
  SEDNA_OPERATION_SUCCEEDED
  SEDNA_QUERY_FAILED
  SEDNA_QUERY_SUCCEEDED
  SEDNA_RESET_ATTRIBUTES_SUCCEEDED
  SEDNA_RESULT_END
  SEDNA_ROLLBACK_TRANSACTION_FAILED
  SEDNA_ROLLBACK_TRANSACTION_SUCCEEDED
  SEDNA_SESSION_CLOSED
  SEDNA_SESSION_OPEN
  SEDNA_SET_ATTRIBUTE_SUCCEEDED
  SEDNA_TRANSACTION_ACTIVE
  SEDNA_UPDATE_FAILED
  SEDNA_UPDATE_SUCCEEDED



=head1 SEE ALSO

Mention other useful documentation such as the documentation of
related modules or operating system documentation (such as man pages
in UNIX), or any relevant external documentation such as RFCs or
standards.

If you have a mailing list set up for your module, mention it here.

If you have a web site set up for your module, mention it here.

=head1 AUTHOR

Daniel Ruoso, E<lt>ruoso@E<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2010 by Daniel Ruoso

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.10.0 or,
at your option, any later version of Perl 5 you may have available.


=cut
